# Runs the python script to ingest metrics into the database

name: Ingestion Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - run: pip install -r .github/scripts/ingestion-data/requirements.txt
    - run: python .github/scripts/ingestion-data/main.py
    - uses: stefanzweifel/git-auto-commit-action@v4
